# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # VirtualBox.
  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.cpus = 2
  end

  config.vm.synced_folder "../", "/etc/ansible/roles/role_under_test", type: 'rsync'

  ["stretch", "buster"].each do |release|
    config.vm.define "#{release}" do |node|
      node.vm.hostname = "#{release}"
      node.vm.box = "debian/#{release}64"

      # Ansible.
      node.vm.provision "ansible_local" do |ansible|
        ansible.install_mode = "pip"
        ansible.version = "2.4.4.0"
        ansible.playbook = "/etc/ansible/roles/role_under_test/tests/test.yml"
        ansible.become = true
        ansible.compatibility_mode = "2.0"
      end
    end
  end

end
