---
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: buster64
    box: debian/buster64
  - name: bullseye64
    box: debian/bullseye64
lint: |
  set -e
  yamllint .
  ansible-lint --exclude molecule/default/tests
provisioner:
  name: ansible
  become: true
verifier:
  name: goss
