---
driver:
  name: vagrant
platforms:
  - name: debian13
    box: debian/trixie64
  - name: debian12
    box: debian/bookworm64
provisioner:
  name: ansible
  ansible_args:
    - --diff
  become: true
