---
driver:
  name: vagrant
platforms:
  - name: debian12
    box: debian/bookworm64
  - name: debian11
    box: debian/bullseye64
provisioner:
  name: ansible
  ansible_args:
    - --diff
  become: true
